version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: voice_diary_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: voice_diary_db
    volumes:
      - mongo_data:/data/db
    networks:
      - voice-diary-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: voice_diary_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - voice-diary-net

  redis:
    image: redis
    container_name: voice_diary_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - voice-diary-net


networks:
  voice-diary-net:
    driver: bridge

volumes:
  mongo_data:
  minio_data: