[project]
name = "identity-service"
version = "0.1.0"
dependencies = [
    "fastapi",
    "shared-storage"
]

[tool.uv.sources]
shared-storage = { workspace = true }
shared-messaging = { workspace = true }